version: '3.5'
services:
  keyfilekeeper_frontend_dev:
    image: node:12-alpine
    container_name: keyfilekeeper_frontend_dev
    working_dir: /app
    command: tail -f /dev/null
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    stdin_open: true
